import type { Metadata } from "next";
import type { ReactNode } from "react";
import { GeistMono } from "geist/font/mono";
import "@fontsource-variable/fraunces/full.css";
import "@fontsource-variable/fraunces/full-italic.css";
import "@fontsource-variable/archivo/index.css";
import "./globals.css";

/**
 * Fonts come from `@fontsource-variable/*` rather than `next/font/google`.
 * Both self-host, but the Google loader reaches out to fonts.googleapis.com at
 * build time — and this app is built three times in CI by the screenshot and
 * verify harnesses, on runners where a cold font fetch is one more thing that
 * can fail for reasons unrelated to the page. The packages ship the files, so
 * the build is offline either way.
 *
 * `fraunces/full.css` rather than `fraunces/index.css`: the "full" build is the
 * one carrying every axis. Fraunces is not just a weight axis — it has `opsz`,
 * `SOFT` and `WONK`, and the whole reason to choose it over a static serif is
 * that those are addressable. `index.css` ships weight only, and the
 * `font-variation-settings` in `lib/tokens.ts` would silently do nothing.
 *
 * The italic file is imported because the headline actually uses it. Without a
 * real italic face the browser synthesises one by shearing the roman, and on a
 * high-contrast serif at display size that is glaringly obvious — the stress
 * goes the wrong way and the thin strokes smear. A synthesised italic is the
 * kind of defect that survives every gate in this repo, because all of them
 * read source.
 *
 * `GeistMono` stays for figures only, which is why it is still worth a
 * dependency: it is a mono with real tabular figures, and every number on this
 * page sits in a column that has to line up.
 */
export const metadata: Metadata = {
  title: "Bellwether — rehearse the migration before it runs",
  description:
    "Replay a schema change against a slice of real production traffic, watch what it locks and for how long, and get a verdict before it touches the primary. A demo page generated by the frontend-design-pro skill pack.",
};

export interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={GeistMono.variable}>
      <body className="bg-surface-page text-ink antialiased">{children}</body>
    </html>
  );
}
